language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
sudo: enabled
addons:
  postgresql: "10.5"
before_script:
  - psql -c "create database aries;" -U postgres // your database name
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'beerstore'"
services:
  - postgresql